<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;
/**
 * AwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardRepository extends EntityRepository
{
   public function getThreeLastAward()
   {
       $qb = $this->createQueryBuilder('a')
           ->orderBy('a.date', 'DESC')
           ->setMaxResults(3)
           ->getQuery()->getResult(Query::HYDRATE_ARRAY);

       return $qb;
   }

}
