<?php

namespace AppBundle\Repository;

/**
 * CardTraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTraitRepository extends \Doctrine\ORM\EntityRepository
{
}
