<?php

namespace AppBundle\Repository;

/**
 * CreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditRepository extends \Doctrine\ORM\EntityRepository
{
}
