<?php

namespace AppBundle\Repository;

/**
 * JudgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JudgeRepository extends \Doctrine\ORM\EntityRepository
{
}
