<?php

namespace AppBundle\Repository;

/**
 * ProjectRatingMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRatingMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
