<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;

/**
 * ProjectRatingMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRatingMemberRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Project      $project
     *
     * @param string|null  $category
     * @param boolean|null $isVoteJudge
     *
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAverage(Project $project, $category = null, $isVoteJudge = null)
    {
        $q = $this->createQueryBuilder('prm')
            ->select('avg(r.value)')
            ->innerJoin('prm.rating', "r")
            ->innerJoin("r.category", "c")
            ->where('prm.project = :project')
            ->setParameter('project', $project);

        if ($category !== null) {
            $q->AndWhere('c.libelle = :libelle')
                ->setParameter('libelle', $category);
        }

        if ($isVoteJudge !== null) {
            $q->AndWhere('prm.voteJudge = :bool')
                ->setParameter('bool', $isVoteJudge);
        }

        return round($q->getQuery()->getSingleScalarResult() * 10);
    }
}
