<?php

namespace AppBundle\Repository;

/**
 * TypeCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
