<?php

namespace AppBundle\Repository;

/**
 * TypeAgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAgencyRepository extends \Doctrine\ORM\EntityRepository
{
}
